### ISSUE TITLE
Feature Request: Support additional API URI's via file or ENV configuration

### ISSUE THREAD

**Issue by arrrgi** [knrdl/docker-socket-protector#1]
Hey @knrdl 

I stumbled on this project as I was looking for way to better secure my Docker socket and noticed that you support proxying Traefik access to the Docker socket via a small set of the Docker Engine API endpoints. I wonder if you would consider opening this up to conditionally allow other API URI's via config file or environment vars for the container.

This could then allow other applications like Watchtowerr or Portainer to be conditionally granted access to the API endpoints they need, while leaving all other disabled by setting a boolean flag. You could also refer to https://github.com/fluencelabs/docker-socket-proxy/blob/master/haproxy.cfg which has a more exhaustive version of URI filters.

I see this is how the Tecnativa Docker socket proxy also operates but both of these solutions are built on an older version of HAProxy.

I'd love to contribute but sadly know zero Golang to open a PR up for this request sorry.

**Comment by knrdl** [comment]
Hi, thanks for your interest in this little side project. I designed it to be as minimal as possible. So scope and features are very limited (traefik only). That's why it won't fit your needs. 

You would basically need a three phase process:
1. Record all requests (request urls, methods and bodies) sent by the software in question (e.g. watchtower). Therefore you can use the proxy server software of your choice (no hard dependency on HAProxy here)
2. Build rules from the recorded requests, e.g. replace container ids in urls with regex patterns
3. Configure your proxy server to only allow requests matching the rules

I think configuring this in any proxy software is easier than writing a separate tool.

If you just need a portainer with better permission control, please have a look here: https://github.com/knrdl/caasa

**Comment by arrrgi** [comment]
Thanks for the feedback. I would have been really keen to see your project get **extended** to support the ability to add more rules via a config as your implementation is much more lightweight and fit for purpose than bundling up a full HAProxy install in a container.

I don't use Portainer as I'm proficient with Compose and CLI and I'm already using your project here to replace HAProxy for Traefik. Again, thanks for taking the time to respond. If you know of any other very lightweight proxies that can achieve the same, I'd love to hear!

**Comment by knrdl** [comment]
Maybe you are right. While I am thinking about it a dedicated minimal "docker-socket-protector" could work out. The software needs to be extended with these env vars:
1. `LOG_REQUESTS`: `0` | `1`  (default: `1`) -> whether a request log should be written to stdout (or a log file?)
2. `PROFILE`: e.g. `/profiles/traefik` or `/profiles/watchtower` (default: empty) -> path to a file containing the whitelist rules  which allow requests to be passed. If this env var is not specified all requests are allowed (protocol only mode)

A profile file would be a JSON lines file with records like this:
`{"method": "GET", "urlRegex": "^/v\d+\.\d+/containers/json\?limit=\d+$"}`
Future versions might also allow to analyze the request body ... just an idea. There is also the problem with terminal sessions being handled by websockets (out of scope for now)

That might not be too hard to implement. Maybe I will find the time to do so.
Would this basic approach already fit your needs?

**Comment by arrrgi** [comment]
Yes, could easily work with that!

**Comment by knrdl** [comment]
@arrrgi I have updated the software accordingly, please have a look.  For tests use the edge tag of the docker image: `knrdl/docker-socket-protector:edge`

If it works well there will be a v2.0.0 release.

**Comment by arrrgi** [comment]
Thanks, I will try that out in the next few days as I've got a few other commitments. I'll let you know how my testing goes.

**Comment by arrrgi** [comment]
Hi @knrdl 

All good so far. I test using the latest edge image with the following rule file contents:

```
# Method Path
GET /v\d+\.\d+/containers/json\?limit=\d+
GET /v\d+\.\d+/containers/[0-9a-fA-F]+/json
GET /v\d+\.\d+/events\?filters=%7B%22type%22%3A%7B%22container%22%3Atrue%7D%7D
GET /v\d+\.\d+/networks
GET /v\d+\.\d+/networks\?filters=.+
GET /v\d+\.\d+/version
GET /v\d+\.\d+/services
GET /v\d+\.\d+/tasks
GET /containers/[0-9a-zA-Z]+/stats\?stream=false
GET /containers/json\?all=true
GET /containers/[0-9a-zA-Z]+/json
```

**Environment used to validate:**

- Container 1: traefik:2.9.8
- Container 2: ghcr.io/benphelps/homepage:v0.6.10 

I'll test the Traefik Hub agent on my other server, I'm not expecting any issues though. If you're happy to wait another day for me to test that scenario before closing this as complete and releasing, I'll gladly test overnight here.

**Comment by knrdl** [comment]
Please take your time to test.

**Comment by arrrgi** [comment]
Also validate this is working as expected with a number of other tools that interact with the Docker socket for both POST and GET operations.

If you're happy without switching to JSON for the profile files then I'd say it's good now to cut a new release and container image. Let me know if you decide to also switch the profile format to JSON and I can test again

**Comment by arrrgi** [comment]
No problem. I'll do that in the next few days 👍🏻

**Comment by arrrgi** [comment]
Thank you for making the extra time and effort to pull that together. This is definitely a simpler and yet more powerful approach compared to the existing HAProxy based solutions. Job well done!
