### ISSUE TITLE
Portainer profile don´t work

### ISSUE THREAD

**Issue by Akruidenberg** [knrdl/docker-socket-protector#5]
The current profiles for portainer don’t work for me.

`2023/04/18 18:20:42 Profile rule is invalid: GET         (/v\d+\.\d+)?/containers/[0-9a-fA-F]+/(json|top|logs|stats).*$`

**Comment by knrdl** [comment]
I've fixed the broken portainer profiles (https://github.com/knrdl/docker-socket-protector/commit/119efd8c74de3496daeb1f21a76f1c725eff7aad). Please try again with the image: `knrdl/docker-socket-protector:edge` (edge tag)

If it works for you there will be a v2.0.1 release promptly.
